# Sample values for testing the chart rendering
name: users-microservice
namespace: default
replicaCount: 2
image:
  repository: quay.io/lotp/users-microservice-is:001-amd64
  tag: stable
  pullPolicy: IfNotPresent
ports:
  containerPort: 8080
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
route:
  enabled: false
autoscaling:
  enabled: false
job: null
servicemonitor: null
podLabels: {}
podAnnotations: {}
env: []
serviceAccount:
  create: false

